GET  https://murmuring-everglades-92656.herokuapp.com/api/persons
Content-Type: application/json

###
POST https://murmuring-everglades-92656.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Arto Foobar",
  "number": "555 555 5555"
}

###
POST https://murmuring-everglades-92656.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Trish",
  "number": "555 555 5553"
}
###
GET  http://localhost:3001/api/persons/
Content-Type: application/json
###
DELETE   http://localhost:3001/api/persons/601c201b17354692224211a1
# Content-Type: application/json
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "dingus mcgee",
    "number": "111111111111"
}
###
PUT http://localhost:3001/api/persons/601c35d9626905a41d90d208
Content-Type: application/json

{
    "name": "Trish",
    "number": "12377777777777"
}

